# Generated by Django 4.2.3 on 2023-08-21 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_message_is_active_alter_message_edit_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
